[package]
name = "zero_pass_app"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zero_pass_backend = "0.0.5"

[dependencies.gtk]
package = "gtk4"
version = "0.2.0"
